project:
  type: website
  preview: 
    port: 4200


language: "custom-pt-br.yml"
lang: pt

website:
  title: "R-Ladies São Paulo"
  reader-mode: true
  site-url: "https://rladies-sp.org"
  twitter-card:
    creator: "@beamilz"
    site: "@RLadiesSaoPaulo"
  favicon: "img/logo.jpg"
  google-analytics: "G-EB5DDC6HCJ"
  description: "Site da R-Ladies São Paulo, com informações sobre a comunidade e textos escritos por participantes."
  page-footer: 
    right: "Página criada com [Quarto](https://quarto.org/). "
    left: "&copy; Copyright 2022, R-Ladies São Paulo"
    background: "#562457"  
  page-navigation: true  
  repo-url: https://github.com/R-Ladies-Sao-Paulo/blog/
  repo-actions: [edit, issue]  
  margin-header: "subscribe.html"  
  # sidebar: 
  # 
  #   style: "docked"
  #   search: true
  #   border: true
  #   foreground: "#562457" 
  #   alignment: "center"
        
    
      
  navbar:
    logo: "img/logo.jpg"
    background: "#562457" 
    left:
      - text: "Página inicial"
        href: /         
      - text: "Sobre a R-Ladies SP"
        href: sobre.qmd  
      - text: "Como participar?"
        href: como-participar.qmd          
      - text: "Como contribuir com o blog?"
        href: contribuir-com-o-blog.qmd       
      - text: "Sugestão de conteúdos"
        href: sugestoes.qmd           
    right:
      - icon: twitter
        href: https://twitter.com/rladiessaopaulo
      - icon: instagram
        href: https://instagram.com/rladiessaopaulo
      - icon: youtube
        href: https://www.youtube.com/c/RLadiesS%C3%A3oPaulo
      - icon: person-plus
        href: https://www.meetup.com/rladies-sao-paulo/
      - icon: envelope
        href: mailto:saopaulo@rladies.org
      - icon: rss
        href: index.xml        
      - icon: github
        menu:
          - text: "GitHub da R-Ladies São Paulo"
            url:  https://github.com/R-Ladies-Sao-Paulo      
          - text: "Código fonte deste site"
            url:  https://github.com/R-Ladies-Sao-Paulo/blog        


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fontsize: "15pt"
    footnotes-hover: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.rladies-sp\.org\/**'
    citations-hover: true


editor: visual

execute:
  freeze: true
  
comments:
  giscus: 
    repo: R-Ladies-Sao-Paulo/blog