---
title: "Como fazer parte da R-Ladies São Paulo?"
editor: visual
toc: true
comments: false
---

## Participe dos eventos

Os eventos realizados pela R-Ladies São Paulo são gratuitos e são divulgados na plataforma Meetup. Se quiser acompanhar os próximos eventos, recomendamos inscrever-se na plataforma [<i class="fab fa-meetup"></i> Meetup](https://www.meetup.com/rladies-sao-paulo/) e seguir as nossas redes sociais, principalmente o [<i class="fab fa-instagram"></i> Instagram](https://instagram.com/RLadiesSaoPaulo).

    
## Eventos anteriores

As gravações dos eventos que acontecem online ficam disponíveis no canal do [<i class="fab fa-youtube"></i> Youtube](https://www.youtube.com/c/RLadiesSãoPaulo).

    
    

## Grupo no Telegram

Existe um grupo no telegram da R-Ladies São Paulo! O acesso é apenas para pessoas que fazem parte do público-alvo da R-Ladies: mulheres cis, mulheres trans, homens trans, pessoas não-binárias e queer. 

Portanto, o grupo não é aberto, portanto é necessário solicitar o convite. Caso você faça parte do público-alvo e queira participar do grupo, solicite o convite enviando uma mensagem privada no nosso perfil do [<i class="fab fa-instagram"></i> Instagram](https://instagram.com/RLadiesSaoPaulo).


<!-- inicio font awesome -->

```{=html}
<script src="https://kit.fontawesome.com/1f72d6921a.js" crossorigin="anonymous"></script>
```
<!-- final font awesome -->